# Generated by Django 5.2.6 on 2025-12-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการตรวจสอบ'), ('AVAILABLE', 'พร้อมใช้งาน'), ('BOOKED', 'ถูกจองแล้ว'), ('MAINTENANCE', 'ซ่อมบำรุง'), ('REJECTED', 'ไม่อนุมัติ')], default='PENDING', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=50, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(max_length=50, verbose_name='รุ่น')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีจดทะเบียน')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='คำอธิบายรถ')),
                ('car_type', models.CharField(choices=[('SEDAN', 'รถเก๋งขนาดเล็ก'), ('TRUCK', 'รถกระบะ'), ('VAN', 'รถตู้'), ('EV', 'รถไฟฟ้า')], default='SEDAN', max_length=10)),
                ('service_type', models.CharField(choices=[('SELF_DRIVE', 'ขับเอง'), ('WITH_DRIVER', 'พร้อมคนขับ')], default='SELF_DRIVE', max_length=20)),
                ('license_plate', models.CharField(default='', help_text='ทะเบียนรถ (Admin only)', max_length=100)),
                ('transmission', models.CharField(choices=[('AUTO', 'เกียร์อัตโนมัติ'), ('MANUAL', 'เกียร์ธรรมดา')], default='AUTO', max_length=10, verbose_name='ระบบเกียร์')),
                ('fuel_system', models.CharField(choices=[('GASOLINE', 'เบนซิน'), ('DIESEL', 'ดีเซล'), ('LPG', 'LPG'), ('NGV', 'NGV'), ('ELECTRIC', 'ไฟฟ้า (EV)'), ('HYBRID', 'ไฮบริด')], default='GASOLINE', max_length=20)),
                ('num_doors', models.PositiveIntegerField(default=4, verbose_name='จำนวนประตู')),
                ('num_luggage', models.PositiveIntegerField(default=2, verbose_name='จำนวนสัมภาระ')),
                ('has_child_seat', models.BooleanField(default=False)),
                ('accessory_price', models.DecimalField(decimal_places=2, default=0, help_text='ราคาอุปกรณ์เสริมต่อวัน', max_digits=10)),
                ('country', models.CharField(default='ประเทศไทย', max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_option', models.CharField(choices=[('NONE', 'ไม่มีส่วนลด'), ('FIRST_TIMER_20', 'ส่วนลด 20% สำหรับผู้เช่าครั้งแรก'), ('WEEKLY_10', 'เช่า 7 วัน ลด 10%')], default='NONE', max_length=50)),
                ('min_rental_days', models.PositiveIntegerField(default=1)),
                ('max_rental_days', models.PositiveIntegerField(default=30)),
                ('doc_registration', models.FileField(blank=True, null=True, upload_to='car_docs/registration/', verbose_name='เล่มทะเบียน')),
                ('doc_insurance', models.FileField(blank=True, null=True, upload_to='car_docs/insurance/', verbose_name='กรมธรรม์')),
                ('num_seats', models.PositiveIntegerField(default=5)),
                ('rules', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_rental.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('confirmed', 'ยืนยันแล้ว (มัดจำแล้ว)'), ('completed', 'จบงาน (คืนรถแล้ว)'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_ref', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.guestcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_rental.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('OWNER', 'Owner')], default='MEMBER', max_length=10)),
                ('status', models.CharField(default='active', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('approved_status', models.CharField(default='pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rental.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='car_rental.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
