# Generated by Django 5.2.6 on 2025-12-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.15, help_text='ใส่เป็นทศนิยม เช่น 0.15 คือ 15%, 0.30 คือ 30%', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
