# Generated by Django 5.2.6 on 2025-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='daily_rate',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'รถเก๋งขนาดเล็ก'), ('TRUCK', 'รถกระบะ'), ('VAN', 'รถตู้'), ('EV', 'รถไฟฟ้า')], default='SEDAN', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
