# Generated by Django 5.2.6 on 2025-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_booking_discount_amount_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติจากเจ้าของรถ'), ('approved', 'อนุมัติแล้ว (รอชำระเงิน)'), ('confirmed', 'จองสำเร็จ'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'จบการเช่า')], default='pending', max_length=20),
        ),
    ]
