# Generated by Django 5.2.6 on 2025-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_rename_daily_rate_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'พร้อมใช้งาน'), ('BOOKED', 'ถูกจองแล้ว'), ('MAINTENANCE', 'ซ่อมบำรุง')], default='AVAILABLE', max_length=20),
        ),
    ]
