# Generated by Django 5.2.6 on 2025-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='service_type',
            field=models.CharField(choices=[('SELF_DRIVE', 'ขับเอง'), ('WITH_DRIVER', 'พร้อมคนขับ')], default='SELF_DRIVE', max_length=20),
        ),
    ]
