# Generated by Django 5.2.6 on 2025-12-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_photos/')),
                ('description', models.CharField(blank=True, help_text='ระบุตำแหน่ง เช่น กันชนหน้าขวาบุบ', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='car_rental.booking')),
            ],
        ),
    ]
