# Generated by Django 5.2.6 on 2025-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_car_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='Bangkok', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(default='ประเทศไทย', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
