# Generated by Django 5.2.6 on 2025-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_car_city_car_country_car_state_car_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='car_pics'),
        ),
    ]
