# Generated by Django 5.2.6 on 2025-10-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_car_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image1',
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_rental.car')),
            ],
        ),
    ]
