# Generated by Django 5.2.6 on 2025-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_alter_renterreview_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
