# Generated by Django 5.2.6 on 2025-10-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0008_remove_car_image1_alter_car_description_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
