# Generated by Django 5.2.6 on 2026-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0008_profile_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'รอชำระเงิน'), ('WAITING_VERIFY', 'รอตรวจสอบสลิป'), ('COMPLETED', 'ชำระเงินสำเร็จ'), ('EXPIRED', 'หมดเวลา'), ('FAILED', 'ล้มเหลว')], default='PENDING', max_length=20),
        ),
    ]
