# Generated by Django 5.2.6 on 2025-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0009_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
