# Generated by Django 5.2.6 on 2026-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.IntegerField(default=100, verbose_name='จำกัดสิทธิ์'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='ใช้ไปแล้ว'),
        ),
    ]
