# Generated by Django 5.2.6 on 2025-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accessory_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_system',
            field=models.CharField(default='GASOLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='has_child_seat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='max_rental_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='car',
            name='min_rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='num_doors',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='num_luggage',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
