# Generated by Django 5.2.6 on 2026-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_promotion_is_active_promotion_usage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doc_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='car_documents/', verbose_name='สำเนาบัตรประชาชน'),
        ),
    ]
