# Generated by Django 5.2.6 on 2025-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_car_accessory_price_car_fuel_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_option',
            field=models.CharField(choices=[('NONE', 'ไม่มีส่วนลด'), ('FIRST_TIMER_20', 'ส่วนลด 20% สำหรับผู้เช่าครั้งแรก')], default='NONE', max_length=50),
        ),
    ]
