# Generated by Django 5.2.6 on 2026-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0012_car_doc_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
