# Generated by Django 5.2.6 on 2025-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0012_car_discount_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
