# Generated by Django 5.2.6 on 2025-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_car_is_published_car_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
