# Generated by Django 5.2.6 on 2026-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่ามัดจำ (จ่ายหน้างาน)'),
        ),
    ]
