# Generated by Django 5.2.6 on 2025-11-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_alter_car_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(default='ประเทศไทย', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
