# Generated by Django 5.2.6 on 2026-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_car_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_account_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อบัญชี'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขบัญชี'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ธนาคารที่ขอรับเงินคืน'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='refund_slips/', verbose_name='หลักฐานการโอนคืน'),
        ),
    ]
