# Generated by Django 5.2.6 on 2025-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_alter_car_country_alter_car_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
