# Generated by Django 5.2.6 on 2026-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_booking_refund_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติจากเจ้าของรถ'), ('approved', 'อนุมัติแล้ว (รอชำระเงิน)'), ('waiting_verify', 'แจ้งโอนแล้ว (รอตรวจสอบ)'), ('confirmed', 'จองสำเร็จ'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('completed', 'จบการเช่า'), ('refund_requested', 'รอคืนเงิน')], default='pending', max_length=20),
        ),
    ]
