# Generated by Django 5.2.6 on 2025-11-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_system',
            field=models.CharField(choices=[('GASOLINE', 'เบนซิน'), ('DIESEL', 'ดีเซล'), ('LPG', 'LPG'), ('NGV', 'NGV'), ('ELECTRIC', 'ไฟฟ้า (EV)'), ('HYBRID', 'ไฮบริด')], default='GASOLINE', max_length=20),
        ),
    ]
