# Generated by Django 5.2.6 on 2026-01-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0017_promotionusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='accessory_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_child_seat',
        ),
    ]
