# Generated by Django 5.2.6 on 2025-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0017_alter_car_fuel_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('SEDAN', 'รถเก๋งขนาดเล็ก'), ('TRUCK', 'รถกระบะ'), ('VAN', 'รถตู้'), ('EV', 'รถไฟฟ้า')], max_length=10, null=True),
        ),
    ]
