# Generated by Django 5.2.6 on 2025-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'รถเก๋งขนาดเล็ก'), ('TRUCK', 'รถกระบะ'), ('VAN', 'รถตู้'), ('EV', 'รถไฟฟ้า')], default='SEDAN', max_length=10),
        ),
    ]
