# Generated by Django 5.2.6 on 2026-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_remove_car_accessory_price_remove_car_has_child_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายรถ'),
        ),
    ]
