# Generated by Django 5.2.6 on 2026-01-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_alter_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='is_cover',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='approved_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='promotionusage',
            name='used_at',
        ),
    ]
