# Generated by Django 5.2.6 on 2025-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'พร้อมใช้งาน'), ('PENDING', 'รอดำเนินการ'), ('BOOKED', 'ถูกจองแล้ว'), ('MAINTENANCE', 'ซ่อมบำรุง')], default='PENDING', max_length=20),
        ),
    ]
