# Generated by Django 5.2.6 on 2025-11-28 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_alter_car_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='doc_insurance',
            field=models.FileField(blank=True, null=True, upload_to='car_docs/insurance/', verbose_name='กรมธรรม์'),
        ),
        migrations.AddField(
            model_name='car',
            name='doc_registration',
            field=models.FileField(blank=True, null=True, upload_to='car_docs/registration/', verbose_name='เล่มทะเบียน'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AUTO', 'เกียร์อัตโนมัติ'), ('MANUAL', 'เกียร์ธรรมดา')], default='AUTO', max_length=10, verbose_name='ระบบเกียร์'),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='accessory_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ราคาอุปกรณ์เสริมต่อวัน', max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='ยี่ห้อ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='คำอธิบายรถ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='discount_option',
            field=models.CharField(choices=[('NONE', 'ไม่มีส่วนลด'), ('FIRST_TIMER_20', 'ส่วนลด 20% สำหรับผู้เช่าครั้งแรก'), ('WEEKLY_10', 'เช่า 7 วัน ลด 10%')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='', help_text='ทะเบียนรถ (Admin only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='รุ่น'),
        ),
        migrations.AlterField(
            model_name='car',
            name='num_doors',
            field=models.PositiveIntegerField(default=4, verbose_name='จำนวนประตู'),
        ),
        migrations.AlterField(
            model_name='car',
            name='num_luggage',
            field=models.PositiveIntegerField(default=2, verbose_name='จำนวนสัมภาระ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการตรวจสอบ'), ('AVAILABLE', 'พร้อมใช้งาน'), ('BOOKED', 'ถูกจองแล้ว'), ('MAINTENANCE', 'ซ่อมบำรุง'), ('REJECTED', 'ไม่อนุมัติ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีจดทะเบียน'),
        ),
    ]
