# Generated by Django 5.2.6 on 2025-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0021_alter_car_options_car_created_at_car_doc_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='', help_text='ทะเบียนรถ (Admin only)', max_length=100),
        ),
    ]
