# Generated by Django 5.2.6 on 2025-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0022_alter_car_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='num_seats',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
